### ISSUE TITLE
ReadMe documentation (Virtual Machine Inspection through VirtualBox Show) - HTML tags still intact

### ISSUE THREAD

**Issue by santoshpavan** [CSC-DevOps/VM#3]
The Youtube link provided for the demoing of the creation and the demoing of the VM has its HTML tags still intact.

Please refer to the screenshot below.

![image](https://user-images.githubusercontent.com/10775930/106757931-f1565e80-65fe-11eb-9bc5-c5298d4a4fd3.png)

**Comment by chrisparnin** [comment]
This needs to be viewed as a notebook.

**Comment by santoshpavan** [comment]
Ah, my mistake. Thank you.
